### ISSUE TITLE
Unable to create table called `productions`

### ISSUE THREAD

**Issue by andybee** [architect/architect#1111]
**Describe the issue**
If you attempt to name a table `productions`, it's creation will silently fail during Sandbox start-up, presumably due to some kind of catch/formatting of names and the substring `production`?

**Steps to reproduce**
1. Create a project with `@tables` definition of `productions`.
2. Start Sandbox.
3. Attempt to interact with the `productions` table (e.g. `await db._name('productions')`).

**Expected behavior**
`db._name` should return the name of the `productions` table within the local Dynalite instance. Instead `undefined` is returned and inspecting the result of `await arc.tables()` shows no helper methods created.

**Comment by filmaj** [comment]
Can confirm. Interestingly, not an issue with a table named `stagings`. I'm digging into it.

**Comment by filmaj** [comment]
Think I found the issue: https://github.com/architect/functions/blob/master/src/tables/sandbox.js#L22-L23

```
let dontcare = tbl => tbl != 'arc-sessions' && tbl.includes('production') === false
let tables = result.TableNames.filter(dontcare)
```

**Comment by filmaj** [comment]
I think a potential fix is to expand the term we filter table names on in the arc/functions sandbox helper. Instead of filtering out any table with `production` in its logical ID, we can filter out `-production-` since the environment name is embedded as the middle token, separated by hyphens, in the table logical ID. Example logical IDs are `arctest-staging-productions` `arctest-staging-somethingelse` `arctest-production-stagings`, so the format is `<appname>-<environment>-<tablename>`.

**Comment by filmaj** [comment]
Just pushing up the `@architect/functions` v3.13.10 tag now; should be available on npm shortly, and that version should fix this issue. Sorry for the trouble!

**Comment by ryanblock** [comment]
@filmaj thanks for knocking this out! @andybee thanks for filing, and as always keep 'em coming. :)

**Comment by andybee** [comment]
Thanks @filmaj and no trouble, very early on in the impacted project and I now have the exciting job of renaming references to `pr0ductions` in my code 😄
