### ISSUE TITLE
Environment variables gone following deployment after upgrade 8.5.5

### ISSUE THREAD

**Issue by andybee** [architect/architect#1127]
After upgrading to 8.5.5 then attempting a deploy, the deployed Lambda functions no longer have custom environment variables set. They do not appear anywhere in the generated CloudFormation template.

The standard Architect env vars are set correctly. Running `npx arc env` I can see all my vars listed as normal.

I initially thought this might be related to the issues fixed in 8.5.6 regarding HTTP routes that share a source directory, but this issue persisted after upgrading to 8.5.6.

**Comment by filmaj** [comment]
Can confirm that Andy's project uses a local preferences file for env vars. I tried reproducing this using a local project preferences file but env vars end up working properly in a fresh project 🤔  Think this might be a project-specific thing, but let's dig in and see what we can find.

Andy shared some project specifics with me over DM, and there are a few macros included in the project. Andy said the macros, which are supposed to add env vars too, are not adding their env vars, so something seems off here.

Am following up slowly though it'll be async due to timezone differences.
