### ISSUE TITLE
Make destroy idempotent

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#1150]
**Describe the issue**
When destroying an app, Architect may fail; if it successfully destroyed the CloudFormation stack, but not the related resources that aren't managed by CloudFormation (e.g. CloudWatch logs, etc.), `destroy` will bail before looping through and destroying everything else.

Hard to reproduce but here's a term buffer that should provide some insights:

```
✓ [08:47:22] (╯ಠ益ಠ)╯︵~/project/folder
⮑  npx arc destroy --force --app my-app --now
         App ⌁ my-app
      Region ⌁ us-west-2
     Profile ⌁ deploy
     Version ⌁ Architect 8.5.12
         cwd ⌁ /project/folder
⚬ Destroy Destroying staging environment
⚬ Destroy Reminder: if you deployed to production, don't forget to run destroy again with: --production
⚬ Destroy Destroying MyAppStaging immediately, hope you know what you're doing!
⚬ Destroy Destroying MyAppStaging
⚬ Destroy Retrieving deployment bucket...
⚬ Destroy Deleting deployment S3 bucket...
⚬ Destroy Deleting SSM parameters...
⚬ Destroy Deleting CloudWatch log groups...
× Error: Destroy failed; hit max retries
    at Timeout.delay [as _onTimeout] (/project/folder/node_modules/@architect/destroy/src/index.js:176:26)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

✓ [08:51:15] (╯ಠ益ಠ)╯︵~/project/folder
⮑  npx arc destroy --force --app my-app --now
         App ⌁ my-app
      Region ⌁ us-west-2
     Profile ⌁ deploy
     Version ⌁ Architect 8.5.12
         cwd ⌁ /project/folder
⚬ Destroy Destroying staging environment
⚬ Destroy Reminder: if you deployed to production, don't forget to run destroy again with: --production
⚬ Destroy Destroying MyAppStaging immediately, hope you know what you're doing!
⚬ Destroy Destroying MyAppStaging
× ValidationError: Stack with id MyAppStaging does not exist
    at Request.extractError (/project/folder/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/project/folder/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/project/folder/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/project/folder/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/project/folder/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/project/folder/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /project/folder/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/project/folder/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/project/folder/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/project/folder/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

**Comment by ryanblock** [comment]
Also might be helpful: `Destroy failed; hit max retries` – maybe max retries on what operation?

**Comment by filmaj** [comment]
Sorry for the delay from me, been a busy week and been feeling under the weather recently 😞 

So the 'hit max retries' message happens during the CloudFormation stack destroy; we fire off the destroy and then do an exponential backoff on checking if the stack exists asynchronously. If we time out waiting for that to happen, then you'll see this 'hit max retries' message. I like your suggestion, we should qualify what operation is happening in that error message. 

(Aside here: I think the reason we don't see an entry in your terminal output for "Deleting CloudFormation Stack" or some such is because we use [`updater.start` at the beginning of the CFN Stack destroy](https://github.com/architect/destroy/blob/master/src/index.js#L148), which starts a little CLI indicator/animation. The next call to `updater` then "wipes out" the previous output line, so we effectively lose one line of output.)

The very first AWS API interaction in destroy is [calling `describeStack`](https://github.com/architect/destroy/blob/master/src/index.js#L65), which is where the error occurs on your second run through. My guess is `arc destroy` hit its timeout limit waiting on the stack to destroy on the first run, but then shortly afterward the stack completed destroying itself, so on the second run through, the stack is gone, and thus the first call to `describeStack` fails.

Couple ideas on what we could do better here:

1. What about bumping up the timeout on the call to `destroyStack` - or even eliminating it altogether? Sometimes CFN destroys take a while, but I don't see why `arc destroy` needs to have a set limit on how long it'll wait. I think I prefer removing the timeout on this, especially as I look to tackle a client project involving creating and destroying stacks in a CI environment. I would rather not have a CI pipeline get into a half-clean state due to arbitrary timeout values. Another related option is make the timeout configurable with a CLI flag? Or even provide a special CLI flag to not use a timeout at all? Thoughts?
2. I like your intention of making the destroy command idempotent. It looks like we can inspect the `describeStack` error to see if it returns a 'stack not found' error (we already do so for the final destroy polling), so [the initial call to describe the stack](https://github.com/architect/destroy/blob/master/src/index.js#L65) can be changed to handle the case where the stack does not exist. The other non-stack resources that we handle deletion of (cloudwatch logs, deployment bucket, SSM parameters) should be idempotent already. I think the only other thing we'd have to tweak is [the call to `describeStackResources` to check if the stack contains DynamoDB tables](https://github.com/architect/destroy/blob/master/src/index.js#L128) - but to be honest I don't like that we do this so late in the logic waterfall (the final step before deleting the stack). Perhaps we can move this up to right after the call to `describeStack`?

Lots to chew on here. Curious on your thoughts.

**Comment by filmaj** [comment]
I put a PR together related to this issue: https://github.com/architect/destroy/pull/14

Just handles the 'more idempotency' aspect of this issue, I didn't tackle any change to the timeout timer I discussed earlier.

**Comment by ryanblock** [comment]
Some additional context: I hit the `Destroy failed; hit max retries` when working with an Arc project that had some custom CloudFormation that generated some very slow to create/destroy resources. So I'm not surprised that I hit this message, and not surprised that things worked ok under the hood, and I think continuing to exponentially back off could have resulted in a super inefficient use of time during the destroy operation.

> My guess is arc destroy hit its timeout limit waiting on the stack to destroy on the first run, but then shortly afterward the stack completed destroying itself

Yeah, I'm pretty sure that's what happened in this case.

> What about bumping up the timeout on the call to destroyStack - or even eliminating it altogether?

I think it would be good to get confirmation on the most common cases that the stack successfully destroyed, especially since some stacks sometimes do not successfully destroy. I'm not sure what the best approach is here because in think long waits on `destroyStack` are probably pretty uncommon. But by making this a userland setting, we're expecting users to have some idea how long such a call ought to take, which seems unrealistic. idk!

> I don't like that we do this so late in the logic waterfall (the final step before deleting the stack). Perhaps we can move this up to right after the call to `describeStack`?

sgtm!

**Comment by filmaj** [comment]
> But by making this a userland setting, we're expecting users to have some idea how long such a call ought to take, which seems unrealistic. idk!

What about adding a flag such as `--no-timeout` to eliminate a hard limit on the timer, and just indefinitely ping the CloudFormation API to check for the stack until it no longer exists or the destroy failed?

**Comment by filmaj** [comment]
Alright, this has been tackled in destroy 1.2.3 which is now live. I've also spun out the topic of `destroy`'s timeout into its own own issue: https://github.com/architect/architect/issues/1157.
