### ISSUE TITLE
Arc 9.0

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#1153]
In Arc 8.5 and 8.6 we've shipped some great beta releases for our new plugins system (yay @filmaj!).

Additionally, in July and August of 2021 (weeks away from this writing), AWS will begin phasing out `nodejs10.x` (which went EOL in 2020 and stopped receiving security patches in April 2021), `python2.7`, `ruby2.5`, and `dotnetcore2.1` from Lambda.

This summer seems like a great opportunity to ship Architect 9.0!

Also wanted to evaluate what's in the feature backlog and grab bag of other potentially breaking changes. Please post in this thread for discussion!

**Comment by ryanblock** [comment]
New default function config should be for `nodejs14.x`. (Also, perhaps we should have some compat to be able to roll forward Node versions while retaining versions on existing projects. Would go in Deploy I think!)

**Comment by filmaj** [comment]
Oh yeah good point re nodejs compatibility on AWS! Regarding nodejs 14 compat, couldn't we leave that up to the config.arc file in each function directory? Presumably if you have an existing project that was created with arc <9, then the default config.arc runtime value would be nodejs12 (unless you changed that yourself). Couldn't we keep that as-is, but newly-created node functions would default to nodejs14?

Then the act of upgrading an existing project from nodejs 12 to 14 is a user opt-in action (and we could explain how to do this as part of an arc 9 release blog post / upgrade guide).

**Comment by DavideCarvalho** [comment]
Things I think would be good for architect:
- Create better typescript integration. If not, create a template for typescript projects, or document better how to turn the project to typescript
- Better documentation. I don't know you guys, but people I know tend to not give it a try on some stuff if the documentation is not appealing
- Initiate arc projects with [architect functions](https://github.com/architect/functions) library, or make this library into the core project. I don't think I had a case where I didn't need this library
- New alias for updating an arc project. Running arc init again to create new project files doesn't seem right, since I'm not initiating a new project

About the JS API:
- arc.http.async and  arc.queues.subscribe should receive a non async function too. Express or any other framework accepts async and non-async functions, I think this should be the case too.

About the config.arc file, would be great if we have a better DevX. If it isn't viable to create a IDE integration, maybe creating something like [spring initializr](https://start.spring.io/)

**Comment by ryanblock** [comment]
Thanks for the input! Responses below.

> Create better typescript integration. If not, create a template for typescript projects, or document better how to turn the project to typescript

Better TypeScript integration could me a lot of things to a lot of folks. For example, a lot of Arc users use https://www.npmjs.com/package/@types/architect__functions

Perhaps you could expand further on what you'd like to see?

> Better documentation. I don't know you guys, but people I know tend to not give it a try on some stuff if the documentation is not appealing

Our documentation is definitely a long-running pain point.

> Initiate arc projects with architect functions library, or make this library into the core project. I don't think I had a case where I didn't need this library

For the first couple years of the project, we heard user feedback that folks wanted the raw Lambdas, and did not want our abstraction layer by default, and preferred to opt into it. We now make using Arc Functions easier via Lambda treeshaking, but I am reticent to wrap customer code in our helper lib.

> New alias for updating an arc project. Running arc init again to create new project files doesn't seem right, since I'm not initiating a new project

Try `npx arc create`, it does the same thing!

**Comment by filmaj** [comment]
Thanks for your suggestions @DavideCarvalho! My personal opinion on TypeScript and better docs:

- There are many ways to go about using TypeScript with Architect, so I would be reticent to suggest or formally prescribe how to go about doing that. I have [my own personal example project](https://github.com/filmaj/arc-typescript) - but this is just one way of doing it. As such, I am hesitant to try to include any specific method of TS integration in the official Arc docs. Furthermore, I don't tend to use TS at all in my projects, so I am definitely not an expert and most of that area is out of my comfort zone, which makes me even more hesitant to try to include it in any way in Arc.
- Indeed, we get feedback like "I wish your docs were better" quite regularly, but as a maintainer, I also find that feedback not constructive. It's hard for me to take steps to just "make them better". Could you elaborate or be a little more specific on what you think is lacking?

**Comment by DavideCarvalho** [comment]
You guys are right, i'll try to explain more what I wanted to say.

- By better typescript integration, what I meant is maybe when using ``.ts`` files, those files should be compiled when building the project. I say this because a lot of projects, like NextJS, or even serverless framework do it. You see only ``.ts`` files, but those files are compiled when you build the project - like NextJS - or when you deploy it - in the case of serverless framework -. Also, creating a starter template that already have typescript by default would be helpful, since the js community uses TS a lot.

- About the docs, I think that documenting a step-by-step something like a todo app would be great! It would show how to create a project with Architect, updating the project files, creating the tables, maybe also show how to have a scheduled event. I like a lot step-by-step approach because it even helps out newcomers.
Examples of docs that I like: NestJS, BlitzJS, Laravel
Also, maybe revamping the docs to have a landing page, talking about the project would help. Example: NestJS, BlitzJS. I particularly like that NestJS has a code example in codesandbox right on it's landing page

- Talking about DevX, config.arc file doesn't have auto-complete, talking about Webstorm, it understands arc file as a txt file. I guess some kind of extension for VSCode and/or Webstorm would help with that. But I know, this shouldn't be easy, so maybe having a site where you select what you need and it generates an arc file with the correct semantics.

Of course this is just my opinion, sorry about anything and I hope my 2 cents here can you guys in some way.

**Comment by brianleroux** [comment]
Hey @DavideCarvalho ! Some quick considerations. 

- If we compile your typescript we then need to make Typescript then it becomes a dependency of Architect and we'll need to form some opinions on the `tsconfig.json` file which, I think, is out of scope for this project. As of this writing there are potentially hundreds of different combinations of compiler options and this would be huge drain on backwards compatibility which we value highly. We should absolutely provide more guidance on compilers and compiler options for popular choices like TS tho. 
- You gotta check out https://github.com/architect-examples !
- For autocompletion I think you can get some of that from the JSON dialects. Would love some help making this happen. There's only 14 top level pragmas in Architect so our scope is actually quite small…
- No need to apologize! THANK YOU for taking the time to help us get better.

**Comment by filmaj** [comment]
Another thing to tee up for 9.0: we can remove [the deprecation we have in `destroy` for the confusion between the `--app` and `--name` parameters](https://github.com/architect/destroy/blob/master/src/cli.js#L34-L43).

**Comment by ryanblock** [comment]
One more to add to the pile: removing Sandbox's Arc <6 support (aka deprecated mode).

**Comment by ryanblock** [comment]
Creating issues for these in the 9.0 milestone: https://github.com/architect/architect/milestone/13

**Comment by ryanblock** [comment]
One more thing: for a while I've been wanting to set CloudWatch log retention limits, namely to 2 weeks or 1 month. Right now Arc logs could in theory pile up forever and that's left to the user. Perhaps we should add this limit but also release a simple plugin to configure retention limits?

**Comment by filmaj** [comment]
Hmmm, interesting. I've worked with arc for a while and piling up logs has never been an issue for me! Sure, could add that, though I don't think it's massively pressing. Possibly could just release the log retention limit plugin on its own without changing the default, too?

One issue that I think is really important is customizing [the app secret that arc/functions uses for session cookies](https://github.com/architect/functions/blob/master/src/http/session/providers/jwe.js#L10-L11). Arc tooling should most def make a lot of noise about this when creating a new application, and I feel like we owe it to the community to ensure everyone knows this needs customization. Some thoughts:

- `arc create` should log something out to inform the user to customize this.
- suggest users set this via `arc env`? or something else?
- update getting started docs to highlight this

**Comment by ryanblock** [comment]
Note from v9 chat today: @filmaj to add logging/alerting to not having a session token env var set in your app!

**Comment by ryanblock** [comment]
Shipped!
