### ISSUE TITLE
two for one! plugin not hydrating @views and invokeFunction is missing a dev

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#1162]
have a plugin that implements `sandbox.start` and `functions` below; `invokeFunction` call is failing because its missing a dev and the hydration isn't getting `src/views` (grabbing lunch and bbiab to fix)

```javascript
let path = require('path')
let src = path.join(__dirname, '..', 'http', 'get-_entry-catchall')

async function start ({ arc, inventory, invokeFunction, services }) {
  // adds get /_entry route
  services.http.get('/_entry/*', function (req, res) {
    let fn = require(src)
    fn.handler({ pathParameters: { proxy: req.originalUrl }}).then(function(result) {
      res.statusCode = result.statusCode
      res.setHeader('Content-Type', result.headers['content-type'] || 'text/javascript; charset=utf-8')
      res.end(result.body)
    }).catch(function(err) {
      console.log(err) 
      res.setHeader('Content-Type', 'text/plain; charset=utf-8')
      res.end(err.message)
    })
    /*
    invokeFunction({src, payload}, function (err, result) {
      if (err) {
        console.log('plugin-bundle error', err)
      }
      else {
        console.log('got result', result)
      }
      res.end(req.originalUrl)
    })*/
  })
}


module.exports = {
  package: pkg,
  functions: ()=>([{ src }]),
  sandbox: { start }
}
```

**Comment by ryanblock** [comment]
Ok, looking at the repo this is from: https://github.com/architect/plugin-bundle and the two issues outlined:

> hydration isn't getting `src/views`

Plugin functions are just registered as generic Lambdas (like, say, `@events` or `@queues` Lambdas), they aren't classified as `@http`/`get`s, so they wouldn't be in `inv.views`. If `src/shared` can work for this case, that's an option!

Alternately, while I do not recommend doing this, you can mutate the Inventory object to add this function to `inv.views.views` array. I don't foresee that breaking any time soon, but the contract we have in Inventory is that one ought not to mutate Inventory as that object may be liable to change outside userland – probably fine in this case, but if you do do that, probably should wait until after we ship the new version of Sandbox this week, which passes around a single Inventory object instead of reloading it multiple times throughout startup. 

> invokeFunction call is failing because its missing a dev [dep?]

This is not reproducing on my local machine; I uncommented `invokeFunction` as well, and that just doesn't seem to be doing anything, which is strange. But no errors or missing dependencies!

**Comment by ryanblock** [comment]
Quick update: I see what's up now, I was looking for an error in Sandbox, but the error is being delivered to the client. Should be an easy fix!

**Comment by ryanblock** [comment]
Ok, the `update.debug` error should be patched in Sandbox `3.7.0` (fix first appearing in `3.7.0-RC.0`)!

**Comment by ryanblock** [comment]
Oh, almost forgot: @filmaj could use a hand with tests that exercise plugin `invokeFunction`, if you can take a look! I did minorly refactor the plugins stuff into a single test but kept the contents otherwise intact.

**Comment by filmaj** [comment]
@ryanblock sorry, tests in which module did you want me to take a look at?
