### ISSUE TITLE
Plugins API

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#1175]
As of Arc 8.5 (March 2021), we have a [nascent / beta plugins API](https://arc.codes/docs/en/guides/extend/plugins) that folks have used to extend Architect in some pretty dope new ways. It's pretty nice!

So far we support the following methods:

- [**`package`**](https://arc.codes/docs/en/guides/extend/plugins#package) - allows customization of the CloudFormation to be deployed; think of it as taking over for `@macros`, which will be deprecated (but still supported) when Arc plugins are are production-ready
  - supported by `arc deploy`
- [**`functions`**](https://arc.codes/docs/en/guides/extend/plugins#functions) - register new Lambdas for integration with various services
  - supported by `arc create`, `arc deploy`, `arc hydrate`, `arc logs`
- [**`variables`**](https://arc.codes/docs/en/guides/extend/plugins#variables) - add shared data for Lambda to be loaded via `@architect/functions` helper library
  - supported by `arc deploy`, `arc sandbox`
- [**`sandbox`**](https://arc.codes/docs/en/guides/extend/plugins#sandbox.start) - hook into Sandbox's startup (`sandbox.start`) and shutdown (`sandbox.end`) routines
  - supported by `arc sandbox`

I'd like to propose some **new methods and hooks**:

- **`create|init`** - a list of directories to inspect and generate boilerplate source for
  - would be supported by `arc create`, `arc sandbox`
- **`hydrate`**
  - `srcDirs` - a list of directories to hydrate dependencies
  - `start` - hydrate lifecycle hook to run operations prior to hydration
  - `end` - hydrate lifecycle hook to run operations after hydration
  - would be supported by `arc deploy`, `arc hydrate`, `arc sandbox`
- **`sandbox.invoke`**
  - `start` - Lambda invocation lifecycle hook to run prior to Lambda execution
  - `end` - Lambda invocation lifecycle hook to run after Lambda execution
  - would be supported by `arc sandbox`

Other changes I'd like to propose:

- `deploy` - propose renaming `package` to deploy, as for most folks `package` is an under-the-hood Architect workflow that doesn't map with common usage

Any other ideas or use cases we should be thinking about or looking at?

**Comment by brianleroux** [comment]
Love it!

**Comment by filmaj** [comment]
Looks good!

Could you describe what use cases you are solving with these extensions? (I think I know but just for posterity's sake in this issue)

One thing that may or may not be confusing is how `plugin.functions` and `plugin.create` and `plugin.hydrate` could be overlapping. I.e. if I write a plugin that creates Lambdas for something via `plugin.functions`, then when running `arc create` or `arc hydrate`, `plugin.functions` gets invoked. If I now add a `plugin.hydrate` method in addition to `plugin.functions`, now both `plugin.functions` AND `plugin.hydrate` will execute when hydration operations run. Think we'd need to be clear in any documentation about this. Probably need to describe what order these execute in in these double-up situations.

As for additions to these, one use case that has come up while working on a plugin that adds an S3 bucket and S3 Object Lambdas associated to the bucket is: `arc destroy` hook. Would be cool if my plugin could hook in there so that it can delete all the files in the bucket prior to having CloudFormation remove the bucket (otherwise the CFN DeleteStack operation fails as only empty buckets can be deleted).

**Comment by ryanbethel** [comment]
I think we need a plugin hook for registering new http routes in the sandbox. Currently, routes are registered before plugins are run. It is possible to take the http instance that is passed into the plugin and register a new route with it, but you can't take advantage of the http-invoker to pass the route handler to that new route. This requires duplicating all the logic for invoking the handler inside the plugin. A better solution seems like hooking in right before the routes are registered. This only requires the plugin author to provide minimal information about the route and the path to the handler.

**Comment by ryanblock** [comment]
This issue is superseded by #1295; the feedback here is still super valid though, and will (continue to) inform the API!
