### ISSUE TITLE
Document IAM permissions required for AWS CLI user

### ISSUE THREAD

**Issue by trsrm** [architect/architect#1278]
The best practice is AWS is to follow the "least privileges" policy. 
So, I created a separate user for Architect deployment. But it is not clear which IAM permission it with require.
Is it already documented somewhere?

P.S. Of course, it is possible to provide "AdminAccess" - but this is not an option in our case.

**Comment by ryanblock** [comment]
Yikes, this was documented and somehow it must have gotten lost in the shuffle from the docs rewrite last year. (Looks like [Brian spotted this](https://github.com/architect/architect/issues/1112) already.)

tl;dr: `AdministratorAccess` is required. Least-privilege is a concept that applies primarily to runtime – not deployment – roles.

Why:
- Architect cares deeply about security; as such, all resources it provisions are least-privilege by default
  - Example: by default, an Architect-created Lambda can only access DynamoDB tables from within its project
- In order to create least-privilege resources, Architect must be able to create a least-privilege IAM role to attach to Lambdas, etc.
- The ability to create IAM roles is, de facto, equivalent to `AdministratorAccess` level privileges (e.g. if I have access to create IAM roles and assign then, I can create and assign a new role with `AdministratorAccess` privileges)
- Thus, even if your credentials for deploying via Architect were limited only to IAM, CloudFormation, etc., by extension, those credentials are still as good as `AdministratorAccess`

So everyone is welcome to inspect (and mutate) Architect CloudFormation documents to tailor their deployment credentials and ensure those credentials have fewer privileges, but the exercise would be purely performative.

**Comment by trsrm** [comment]
OK. Thanks for the clarification. It would be great if I read this in the documentation 🙂

**Comment by ryanblock** [comment]
@tbeseda is all over it! https://github.com/architect/arc.codes/pull/462

**Comment by ryanblock** [comment]
Fixed in https://github.com/architect/arc.codes/pull/462, thanks for the heads up @trsrm!
