### ISSUE TITLE
@prisma/client did not initialize yet

### ISSUE THREAD

**Issue by dsignzmedia** [architect/architect#1377]
### Discussed in https://github.com/orgs/architect/discussions/1376

<div type='discussions-op-text'>

<sup>Originally posted by **dsignzmedia** September 17, 2022</sup>
Hi,
We are developing an application using Remix and Architect. We want to deploy this application to AWS Lambda. Our application's database is Postgresql and we are using Prisma for database operations.

Using Architect, we were able to deploy the app to AWS Lambda. However, we get this error 

"errorType": "Error",
    "errorMessage": "@prisma/client did not initialize yet. Please run \"prisma generate\" and try to import it again.\nIn case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues",
    "stack": [
        "Error: @prisma/client did not initialize yet. Please run \"prisma generate\" and try to import it again.",
        "In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues",
        "    at new PrismaClient (/var/task/node_modules/.prisma/client/index.js:3:11)",

Any inputs on this would be really helpful.

Also, we are using AWS RDS for Postgresql, and we have given the connection string as DATABASE_URL environment variables. 

I tried to used plugins to include prisma/client, how I am not sure how to provide the prisma generate command in .arc file / package.json.</div>

**Comment by tbeseda** [comment]
I believe the issue is that `prisma generate` is creating some code locally during development and that's not available to whichever Lambda (probably the Remix server function) needs it on AWS. If you run that command from the project root, the client is added to the top-level node_modules folder. So it works in Sandbox during local dev, but isn't available in production.

When Arc deploys, it treats each individual function as its own independent Node package (because that's how it works on AWS Lambda). Arc detects and installs dependencies and hydrates shared code to `@architect/shared/**`.

Anyway, your Prisma client isn't making it.

A couple options:

- create a package.json with all requirements inside the Remix server function and make sure the prisma client makes it into that folder's node_modules/@prisma/
  - this is the most hands-on manual way, but does require some maintenance when your requirements change for that function

- create an Arc plugin, probably `hydrate.copy` (a relatively new addition to Arc!)
  - this plugin runs _after_ Arc does all its hydration, but before deployment. giving you time to move things into a function before it's sent to AWS.

> hydrate.copy runs after all dependency installation and shared file operations are complete, ensuring that any filesystem mutations will be present in final deployment artifacts.

-- [Arc plugins > `hydrate`](https://arc.codes/docs/en/guides/plugins/hydrate)

I think the approach would be to `copy` the @prisma/client/ dir from the project root's node_modules to your server's node_modules folder.

**Comment by tbeseda** [comment]
Follow up tip: if you do try building a plugin that changes deployment behavior but don't want to deploy to AWS over and over, you can run `arc deploy --dry-run` to go through the entire hydrate process, invoke plugins, and generate CloudFormation without actually sending anything to AWS

https://arc.codes/docs/en/guides/plugins/hydrate

**Comment by dsignzmedia** [comment]
@tbeseda thank you for the response. can you share me a sample on how to use hydrate plugin? does the below looks good? 
@hydrate
  copy
    ./node_modules/@prisma/**
    ./server/node_modules/architect/shared/@prisma/**

**Comment by dsignzmedia** [comment]
@tbeseda gentle follow up on this!

**Comment by tbeseda** [comment]
I think I didn't communicate what a plugin is very well.
You write Arc plugins (as CJS) in src/plugins and they can hook into Architect's lifecycle. `hydrate.copy` is a hook.
see here about "private plugins" https://arc.codes/docs/en/guides/plugins/overview
and using a hydrate.copy hook https://arc.codes/docs/en/guides/plugins/hydrate#hydrate.copy-(experimental)

This snippet should help get you started, but I haven't tried deploying with it -- just tested locally with `--dry-run`.  
It tells Architect to copy all of Prisma's hidden node_modules/.prisma directory into each Lambda's node_modules/ folder.

```js
module.exports = {
  hydrate: {
    copy: async ({ copy }) => {
      await copy({
        source: 'node_modules/.prisma',
        target: '.prisma',
      });
    }
  }
}
```

save that as src/plugins/copy-prisma.js

and add it to your app.arc file

```
@plugins
copy-prisma
```

Also, I think a shared directory is required, even if it isn't used. Just add an empty folder called "shared" inside "src/"

**Comment by brianleroux** [comment]
hopefully now resolved but if not pls let us know!
