### ISSUE TITLE
Crash on non- us-west-2

### ISSUE THREAD

**Issue by remy** [architect/architect#1381]
**Describe the issue**

Being in the UK I wanted to deploy a little closer (in my head, that's us-east-1/2), so I destroyed my stack (eventually with `--force`) from `us-west-2`, change the `app.arc` `@aws` section to point to `us-east-1` and deployed.

The deploy process crashes out with a `ValidationError`:

<details>
<summary><strong>Full output</strong></summary>

<pre><code>AWS_PROFILE=arc.code npx arc deploy
         App ⌁ twivatar-arc
      Region ⌁ us-east-1
     Profile ⌁ arc.code
     Version ⌁ Architect 10.7.0
         cwd ⌁ /Users/remy/dev/twivatar-arc

⚬ Hydrate Hydrating dependencies in 1 path
✓ Hydrate Hydrated src/http/get-000username/
  | npm i --production: added 1 package, and audited 2 packages in 515ms
  | npm i --production: found 0 vulnerabilities
  | npm i --production: npm WARN config production Use `--omit=dev` instead.
✓ Hydrate Successfully hydrated dependencies

⚬ Deploy Initializing deployment
  | Stack ... TwivatarArcStaging
  | Bucket .. twivatar-arc-cfn-deployments-a18af
⚬ Deploy Created deployment templates
✓ Deploy Generated CloudFormation deployment
Uploading to 94871b48ebe53daa127d4320f4499f02.template  7159 / 7159.0  (100.00%)
An error occurred (ValidationError) when calling the CreateChangeSet operation: S3 error: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

Uploading to 94871b48ebe53daa127d4320f4499f02.template  7159 / 7159.0  (100.00%)
An error occurred (ValidationError) when calling the CreateChangeSet operation: S3 error: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

    at ChildProcess.<anonymous> (/Users/remy/dev/twivatar-arc/node_modules/@architect/deploy/src/sam/utils/spawn.js:23:16)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:313:12)</code></pre>

</details>

**Steps to reproduce**
1. Deploy using defaults from `arc init`
2. Destroy
3. Change region to `us-east-1` (2 doesn't seem to have the infrastructure to deploy)
4. See error from above detail

**Desktop**
Please complete the following information (if appropriate):
 - OS: macOS Big Sur
 - Version Architect 10.7.0

**Comment by ryanblock** [comment]
Funky. That doesn't look like a familiar error to me, will take a look today!

**Comment by ryanblock** [comment]
Ok, I had a look. The bad news first: it doesn't reproduce for me (details below). I think I know what the issue is, though.

So when you create an Architect app, if you do not specify a deployment bucket (which basically no one does – that's one of the many AWS warts Arc smooths over for folks), we create one for you. To know which deployment bucket we created for your app, we also create a corresponding entry in SSM. So think: `my-app → my-app-bucket-abc123.{region}.s3`. When you delete the app, we also delete the entry (and the bucket).

However, if for whatever reason Arc were unable to complete its app deletion process, that SSM entry could stick around. If it did, the next time an app of the same name (e.g. `my-app`) was created, Arc would still think its deployment bucket was `my-app-bucket-abc123.{region}.s3`, when in fact the region may have changed. And since S3 buckets must be in the same region as the CloudFormation deployment, such a scenario would be likely to produce the error above. (See also [this AWS CLI issue](https://github.com/aws/aws-cli/issues/4512).)

Here's the log of my stuff running through two app create cycles, where the app name is the same and only the region changes between instances. During deletion, note the following three lines, specifically:

```
⚬ Destroy Retrieving deployment bucket...
⚬ Destroy Deleting deployment S3 bucket...
⚬ Destroy Deleting SSM parameters...
```

<details>
<summary><strong>Full output</strong></summary>
<pre><code>
npx arc deploy
         App ⌁ test-1381
      Region ⌁ us-west-2
     Profile ⌁ personal
     Version ⌁ Architect 10.7.0
         cwd ⌁ /Users/ryan/git/architect/_test-projects/1381

✓ Hydrate Finished checks, nothing to hydrate
⚬ Deploy Creating new private deployment bucket: test-1381-cfn-deployments-0b0ae
⚬ Deploy Initializing deployment
  | Stack ... Test1381Staging
  | Bucket .. test-1381-cfn-deployments-0b0ae
⚬ Deploy Created deployment templates
✓ Deploy Generated CloudFormation deployment
⚬ Deploy Deploying static assets...
⚬ Deploy @static folder (public/) not found, skipping static asset deployment
✓ Deploy Deployed & built infrastructure
✓ Success! Deployed app in 123.981 seconds

    https://lt0p091512.execute-api.us-west-2.amazonaws.com

✓ [06:40:58] (╯ಠ益ಠ)╯︵~/git/architect/_test-projects/1381
⮑  npx arc destroy --now --force --app test-1381
         App ⌁ test-1381
      Region ⌁ us-west-2
     Profile ⌁ personal
     Version ⌁ Architect 10.7.0
         cwd ⌁ /Users/ryan/git/architect/_test-projects/1381

⚬ Destroy Destroying staging environment
⚬ Destroy Reminder: if you deployed to production, don't forget to run destroy again with: --production
⚬ Destroy Destroying Test1381Staging immediately, hope you know what you're doing!
⚬ Destroy Destroying Test1381Staging
⚬ Destroy Deleting static S3 bucket...
⚬ Destroy Retrieving deployment bucket...
⚬ Destroy Deleting deployment S3 bucket...
⚬ Destroy Deleting SSM parameters...
⚬ Destroy Deleting CloudWatch log groups...
✓ Destroy Successfully destroyed Test1381Staging

✓ [06:42:12] (╯ಠ益ಠ)╯︵~/git/architect/_test-projects/1381
⮑  npx arc deploy
         App ⌁ test-1381
      Region ⌁ us-east-1
     Profile ⌁ personal
     Version ⌁ Architect 10.7.0
         cwd ⌁ /Users/ryan/git/architect/_test-projects/1381

✓ Hydrate Finished checks, nothing to hydrate
⚬ Deploy Creating new private deployment bucket: test-1381-cfn-deployments-219e2
⚬ Deploy Initializing deployment
  | Stack ... Test1381Staging
  | Bucket .. test-1381-cfn-deployments-219e2
⚬ Deploy Created deployment templates
✓ Deploy Generated CloudFormation deployment
⚬ Deploy Deploying static assets...
⚬ Deploy @static folder (public/) not found, skipping static asset deployment
✓ Deploy Deployed & built infrastructure
✓ Success! Deployed app in 119.052 seconds

    https://1chmgm3axg.execute-api.us-east-1.amazonaws.com
</code></pre></details>

My suspicion is that the resolution here will be for you to try deleting the app one more time (making sure your app name was identical across both runs, and ensuring those SSM parameters + deployment bucket are destroyed); should that not work, I'd ask you to open your AWS console and go inspect the SSM params at `/${Arc formatted appname}/deploy/bucket`. 

Please let me know if that helps!

Oh, one other bit:
> Change region to us-east-1 (2 doesn't seem to have the infrastructure to deploy)

Can you be more specific there? `us-east-2` should absolutely have everything Arc apps use. As should `eu-west-2` (London) fwiw!

**Comment by ryanblock** [comment]
Going to close this for now, please lmk if you spot anything like this again so we can try to repro!
