### ISSUE TITLE
static file upload doesn't preserve subfolder structure in s3 on windows

### ISSUE THREAD

**Issue by r2dliu** [architect/architect#1420]
**Describe the issue**
static file upload to s3 produces flat directory of files and doesn't preserve subfolder structure

May be a windows only thing because it uses the forward slash instead of backslash, haven't tested on mac or linux yet

**Steps to reproduce**
have a project, run arc deploy with static assets, note upload path includes forward slashes instead of back slashes and bucket structure is flat

**Expected behavior**
Preserve file structure

**Screenshots**
![image](https://user-images.githubusercontent.com/10493269/231262154-6be5b98c-8ac2-4569-9797-a57ab1715e0e.png)
screenshot of s3 post deploy (note the backslashes)

**Desktop**
Please complete the following information (if appropriate):
 - Windows 10

**Mobile**
Please complete the following information (if appropriate):

**Additional context**
Add any other context or notes about the problem here

**Comment by ryanblock** [comment]
Which version of Architect is this?

**Comment by r2dliu** [comment]
most recent, Architect 10.11.0

**Comment by ryanblock** [comment]
Thanks! I thought I got all these windows static asset deployments issues after Glob v9, but I guess not!

This should be fixed this week. In the mean time, the immediate workaround is to deploy with *nix, which will not have these path normalization problems.

**Comment by ryanblock** [comment]
This should now be patched in 10.11.2, and the fix was verified on my Windows machine. However, there is a caveat: files published by Windows to S3 that have the broken backslashes in their paths will not be cleaned by Architect prune.

Unfortunately, this means you will have to jump into the console and clear them out (if you care about ensuring their removal, that is). Sorry for that, but I did not want to open up new risk of false-positive nominations of files for deletion.

Thanks for reporting this, @r2dliu!
