### ISSUE TITLE
arc deploy running npm install on the developer's laptop and not the lambda is problematic

### ISSUE THREAD

**Issue by dagda1** [architect/architect#1440]
**Describe the issue**

I am using architect with a  [remix-run](https://remix.run/docs/en/1.19.1) app that uses [mdx-bundler](https://github.com/kentcdodds/mdx-bundler) to turn markdown files into static HTML.

mdx-bundler uses esbuild and I get the following error message:

> Specifically the "@esbuild/darwin-x64" package is present but this platform
needs the "@esbuild/linux-arm64"

This is because the `npm ci` that architect runs before the upload happens on the devs laptop and not the environment where it will be deployed.

**Expected behavior**
A clear and concise description of what you expected to happen

`npm ci` should run on the environment prior to deploy.

This will affect other binaries as wwell.

**Comment by dagda1** [comment]
If you are deploying on docker, you do the `npm ci` in the container, not the host.  I was surprised it did not work the same way.

I got it working by doing the deploy from a github action and not my macbook after a bit of trial and error with the architecture.

BTW, replying with comments like `you don't understand` is a bit high handed and arrogant.

**Comment by ryanblock** [comment]
> If you are deploying on docker, you do the npm ci in the container, not the host. I was surprised it did not work the same way.

Not necessarily, but either way you are not deploying to Docker, you are deploying to AWS Lambda. If you'd prefer to deploy with K8s / Docker, by all means please do that!

>  BTW, replying with comments like you don't understand is a bit high handed and arrogant.

I did not say that, I merely attempted to help explain what was going on since there appeared to be a misalignment of expectations for what Architect does. I asked in good faith how you'd propose we handle this, and I'm happy to field suggestions.

Since you've got things deploying and we don't as yet have any specific feature requests here, I'm going to go ahead and close this issue.
