### ISSUE TITLE
Support CloudFront as an alternative to API Gateway

### ISSUE THREAD

**Issue by lpsinger** [architect/architect#1451]
**Is your feature request related to a problem? Please describe.**
Architect requires an API Gateway to mount the HTTP Lambdas and S3 buckets to various paths in an HTTP origin. For projects that require a CDN, this is redundant: requests must go from CloudFront to API Gateway and then to the function or storage; it would be more efficient for CloudFront to directly route to the Lambda or to S3.

Furthermore, using an API Gateway results in some [very severe resource limitations](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html): responses can be no larger than 10 MB. In my project, we have some responses larger than that which API Gateway cannot server.

**Describe the solution you'd like**
I would like to see the [`apigateway` option](https://arc.codes/docs/en/reference/project-manifest/aws#apigateway) for the [`@aws` pragma](https://arc.codes/docs/en/reference/project-manifest/aws) have a `cloudfront` option that sets up the application with a CloudFront distribution _instead of_ an API Gateway for routing purposes.

**Describe alternatives you've considered**
The only alternative that I can think of for now is to have our application link directly to the origin (the Lambda or the S3 bucket) for HTTP responses that exceed 10 MB. Very ugly, and also a slight security risk because it exposes the ARNs of the buckets and Lambdas, which otherwise would not be publicly discoverable.

**Comment by ryanblock** [comment]
It sounds like the problem at the root of this issue is ingesting very large payloads, which is definitely a use case we've heard, and something that will eventually be resolved by the likely next pragma (`@storage`, see also: https://github.com/architect/architect/issues/1393). I have some initial research into this project complete, and intend to be working on it this year.

As for using CloudFront as an API gateway and not just a CDN, that's a bit of a hack that comes with severe limitations (like the very small number of origin rules). I suspect that'd probably make a better plugin than core Architect feature.

**Comment by lpsinger** [comment]
My use case is a Remix app, which has only _two_ origins: a Lambda and an S3 bucket. So the limited number of origins is not a problem for me.

**Comment by lpsinger** [comment]
If this was implemented as a plugin, it would be a _huge_ plugin! It would entail invasive surgery on the CloudFormation template and changing the arguments passed to http Lambdas. I think that this is not feasible to accomplish as a plugin. It would have to be in the Architect core.

**Comment by shamsup** [comment]
Going through CloudFront + Lambda function URLs also unlocks response streaming, which would allow using features like Remix's deferred API.

**Comment by ryanblock** [comment]
I don't think doing this as a plugin would be that huge of a lift if one used `set.customLambdas` instead of `@http`, but you'd have a difficult time testing it locally. Sandbox support for a CloudFront frontend is completely non-trivial.

While I'm not fundamentally opposed to the idea, practically speaking, even if we had the cycles to prioritize and support this (which we do not as of right now), I don't think it's the view of the maintainers that this is a priority feature.

As ever, if someone else would like to attempt such an implementation, we'd be more than happy to advise and review. I can say that for starters it would necessitate a full implementation of CloudFront [request/response fixtures](https://github.com/architect/req-res-fixtures), and likely a few thousand Sandbox tests to ensure correct implementation, per:
- https://github.com/architect/sandbox/tree/main/test/unit/src/http/invoke-http
- https://github.com/architect/sandbox/tree/main/test/integration/http
