### ISSUE TITLE
Custom named stages (i.e. deploy to different stack names)

### ISSUE THREAD

**Issue by jgallen23** [architect/architect#376]
We want to be able to deploy multiple stagings across our team so we can easily QA a specific feature.  Are there any plans to support something like this? Maybe just adding a suffix to the Lambda Stage name through an ENV var?  We'd be happy to PR if helpful.

**Comment by ryanblock** [comment]
This request has come up from time to time (usually in slightly different ways). The amount of complexity to do so could get absolutely enormous, as could the surface area for bugs and unintentional misuse.

I remain curious though, as this is an area I've given a lot of thought to. Could you break down in detail what you're trying to accomplish, how, and what workflows (Architect, git, CI/CD, etc.) you hope to use to do so?

**Comment by jgallen23** [comment]
The main thing is we have a team of 10 and everybody is working on different things and we want to QA/UAT and let our clients view and sign off the work in isolation.  What we'd like to set up is when somebody on the team creates a PR, we have a build process that deploys to a `[branch-name].[domain]`, then if signed off, we merge PR and it deploys to production.  We currently do this in docker and swarm, but are moving towards a more serverless approach.

**Comment by jgallen23** [comment]
I wonder if its as simple as being able to override the app name from an env var.  We could just add the branch as a suffix to the app and deploy to staging.  I guess we'd have a dynamo data issue, but maybe that could be overridden as well?

**Comment by brianleroux** [comment]
The PR use case is definitely a problem we need to solve.

The early idea with Architect is to be the fastest and easiest path for building database backed web apps serverlessly. So rather than starting with the framework assumption we need to have unlimited configurable stages we instead asked ourselves what are absolute minimum of stages that are required to achieve our goals. (Which became: local preview, local test, staging and production.) Few frameworks give these concepts first class treatment (if at all) usually its a userland problem to solve. So its not surprising we're in this situation but its also important to ack this is a common use case and we should have a good first class solution for it.

I don't mind the idea of changing the .arc file app namespace for this. Each branch could have its name and thusly envs (including yes totally isolated database). This is not a bad way to do it and basically the same complexity you have today manually configuring these things with traditional approaches of some docker/swarm ci pipeline. 

Some further good news: we are in the early stages of adding CloudFormation export which should fit this use case nicely. The PR could run the subject to change command `npx package` to get a `cloudformation.yaml` of the current `.arc` defined reality. CF is pretty easy to deploy (tho rather slow comparatively which is why we're making an eject option).

**Comment by brianleroux** [comment]
Update, we have the first pass of Cloudformation support in the latest arc. Docs coming soon!

**Comment by brianleroux** [comment]
quickstart for 6.x https://gist.github.com/brianleroux/63983d51be7cb053e6463eb07cf480e2

(you can deploy the cloudformation template with any stack name you want)

WIP docs: https://arc.begin.com

**Comment by ryanblock** [comment]
After some discussion, reopening as we consider means to have an official workflow for this (outside the capability of doing it manually with CloudFormation, which comes in Arc 6, ofc).

**Comment by ryanblock** [comment]
Ideas from #429:
> Given an app named `myapp`, running `arc deploy stack foo` should deploy a stack named `MyappFoo`
> Another approach that might be less intrusive is to be able to override the app name with an env var, something like: `ARC_APPNAME=myappfoo arc deploy` would override `myapp` with `myappfoo`

**Comment by brianleroux** [comment]
Thank you for your continued patience! Adding to architect/architect distribution as soon as all the tests pass. You can now tag every deploy with `arc deploy --tags key=val my=hello`!

**Comment by jgallen23** [comment]
thanks! how do Dynamo tables work with this, based on deploy name? also, is a new CDN created for each custom name?

**Comment by brianleroux** [comment]
Both should 'just work' as Dynamo resolves tables thru stackname scoped ssm parameters and Cloudfront also uses stackname to figure out the origin. I'll test a bit more but do lmk if you see anything broken!

**Comment by jgallen23** [comment]
Does it get its own unique stage env vars?  If so, how do I set?

**Comment by brianleroux** [comment]
By default it will be `NODE_ENV` of `staging` and likewise `@staging` environment variables. Deploy with production works likewise.
