### ISSUE TITLE
Documentation for error.js?

### ISSUE THREAD

**Issue by jgallen23** [architect/architect#394]
Just stumbled on this https://github.com/architect/arc-example-errors/blob/master/src/html/get-index/error.js, but I noticed that the repo was archived and I couldn't find any references in the codebase, so I'm not sure if this is still supported.  Is it still supported?  Want some way to show a prettier error page as well as making sure the error is logged.

**Comment by brianleroux** [comment]
no longer needed! the new dep free async functions can trap / display any statusCode/errors 

```javascript
module.exports = async function http(req) {
  try {
    throw Error('uh oh')
  }
  catch(e) {
    return {
      headers: {'content-type': 'text/html'},
      statusCode: 500, 
      body: e.message
  }
}
```
lmk if this helps!

**Comment by jgallen23** [comment]
Any thoughts on trapping errors higher up inside the framework?  Would like to be able to show a friendly error page (nice html page for views and for json routes, don't want stack traces in prod, but want them logged), but don't want to have to wrap every single handler in a try/cache

**Comment by brianleroux** [comment]
totally into it; we did it before because we sorta had no choice given the limits of early api gateway. now that things are reduced to dependency free by default we could look at further augmentation in the optional add on of https://github.com/architect/arc-functions

for now you could prototype by putting logic in `/src/shared` (which gets copied into `/node_modules/@architect/shared` for all lambdas upon deploy or sandbox start).

**Comment by brianleroux** [comment]
closing this for now but if you want to help plan/land something for architect/functions lmk!
