### ISSUE TITLE
req.query missing on a 404 route

### ISSUE THREAD

**Issue by dawnerd** [architect/architect#397]
We've noticed a weird quirk where the query object isn't set at all when a route 404s.

Some example code:

`get-index/index.js`
```js
exports.handler = async function http(req) {
  if (req.path !== '/') {
    console.log(req.query); // undefined
  }
  
  console.log(req.query); // query object
};
```

Make a request like `/will404?paramtest=1234`

We'd expect the query object to contain `paramtest`

**Comment by ryanblock** [comment]
Is this only in `sandbox`, or in real AWS infra as well?

**Comment by dawnerd** [comment]
Should have mentioned, it's on aws. We're seeing it on the production and stage environments

**Comment by brianleroux** [comment]
hey sorry but this is the default behavior of AWS proxy integration (which is how we achieve the catch all instead of getting a 403 w API Gateway) so I'm afraid we can't fix this behavior. here is a link to the relevant aws docs: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format
