### ISSUE TITLE
sandbox generating public when @static folder is set

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#641]
have .arc like this:

```
@app
foo
@static
folder _site
```

and that folder exists. every time I start the sandbox architect generates public files which is annoying.

**Comment by ryanblock** [comment]
Actually a utils issue!

**Comment by ryanblock** [comment]
This is the offending line, but it's only partially the issue: https://github.com/architect/utils/blob/master/fingerprint/index.js#L34-L37

The bigger issue is that this line shouldn't be doing this because `create` only concerns itself with creating `public/` and not `@static folder`: https://github.com/architect/create/blob/master/src/index.js#L57-L62

I'm assuming this was done because the assumption is that if the user defines their own static asset folder with `@static folder`, it must be because they're using some tool that will populate it for them. That makes sense, I wouldn't make that assumption personally.

To not generate that folder means that `get /` requests will be broken until they do, which is a bad experience getting started.

I'd advocate for generating the static asset folder + boilerplate assets with `@static folder` setting or no (and fix that fingerprinting in utils too).

**Comment by ryanblock** [comment]
No longer occurs as of 8.3!
