### ISSUE TITLE
Local dev configuration

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#763]
The last few weeks I've been giving a lot of thought to adding an additional configuration file to Architect. I've been slow to just jump in and lay down code because I (and we) have wanted to be extremely thoughtful and deliberate about adding additional configuration, which is an extremely easy trap to fall into as projects mature.

For reference, here's what we have today in terms of places to set up / configure within Architect:
- **The main Architect project manifest**
  - `.arc`, also `app.arc`, `arc.yaml`, `arc.json`, `arc.toml`
  - Defines your application
- **The Architect env file**
  - `.arc-env`
  - Also [soon possibly with `.env` support](https://github.com/architect/architect/issues/618)
  - Is a local copy of your app's environment variables to populate Sandbox; auto-generated when running `arc env`
- **Per function Arc config files**
  - `.arc-config` (e.g. `src/http/get-index/.arc-config`)
  - Enables granular, per function configuration; enables some functions to be Node.js, while others can be Ruby, etc.
  - Useful for more mature apps where certain routes or events need additional processing power, execution time, etc., or others need less and can save budget

Per https://github.com/architect/architect/issues/732, per-user local dev config has been coming up more and more lately. For example, I like having Sandbox auto-init new project files when my .arc changes, @brianleroux does not – and that's totally valid! We should support both ways of working.

Additionally, I've wanted to add some additional new to Sandbox to make local workflows faster and more flexible; some, like HMR, may benefit from having config; while others, such as hooks to run scripts on filesystem changes, would definitely necessitate additional config.

So here's how I'm thinking of approaching this. `.arc-env` seems like the odd file out, so I would like to create a `.arcrc` (and `.arcrc.js`, etc.) file (or whatever want to name it) that would take over sandbox config (and also be written into by `arc env`).

The structure of that config file would look something along these lines (def open to feedback!):

```
@sandbox
# Don't auto-generate project files from .arc
autoInit false

# Sandbox startup scripts
# Currently paths are non-configurable: scripts/sandbox-startup.[js|py|rb]
startup
  path/to/file/to/execute.js
  another/path/to/file.js

@sandbox-watcher
# Configure folders for the watcher to watch
watch
  public

# Watcher ignore patterns
ignore
  path/to/ignore

# Scripts for the watcher to run
run
  watcher/script/to/execute.js

# The env pragmas below would be managed by `arc env`
@testing
FOO bar
BAZ buz

@staging
FOO bar
BAZ buz
```

Worth noting: Sandbox would continue retain legacy support for `.arc-env`! And if/when I get to `.env` support, the presence of such a file should supersede `.arcrc` as the place to use local env vars.

Anyhow, would love thoughts and feedback on this!

**Comment by brianleroux** [comment]
into all of this but with the request that we please make autoinit false by default and behave more like the newer version of begin.com that mounts a warning html at urls that do not exist

**Comment by brianleroux** [comment]
one other thing: please keep pragmas lowcase dasherized

**Comment by Stegosource** [comment]
Im not sure if this ties into @brianleroux's auto-init project files or not, but when I create a new route, I'll often just copy/paste an entire folder from a route that works sort of similar. In VS Code, it's just `ctrl+c`, `ctrl+v` and results in `/first` and `/first copy` folders. The weird thing, is when I rename the new folder `/second`, I end up with a lot of unsaved files coming from the shared imports of the original route (I hope that's clear). And the annoying thing is now I have to close each of those new files and either save them or close without saving. 

Workflow looks like:
1. Create a route ("/first") with a shared module
2. copy "/first" and paste to same folder
3. Rename "/first" to "/second"
4. At this point, VS code is bombarded with a bunch of new, unsaved files.
5. I close each one, sometimes saving, sometimes not.
6. The code at this point doesnt work, I have to save one of the shared files to trigger `Sandbox Shared file changed, rehydrating functions...`
7. Sometimes I also have to `rm -rf node_modules` then reinstall.

This doesn't happen frequently, but when it does, it's a bit annoying and I'm not sure if there is a better approach. In many cases, it's less work to copy/paste a folder than to create a new function from scratch.

**Comment by ryanblock** [comment]
@Stegosource it sounds like what's happening is you're getting bitten by VS Code's `[javascript|typescript].updateImportsOnFileMove` setting (enabled), but probably not Sandbox itself. You may want to change that setting to `prompt`.

**Comment by Stegosource** [comment]
Yeah, that makes a lot of sense. I do have that turned on. Good thinking :)

**Comment by brianleroux** [comment]
ruminating on this more I'd like to advocate we add to `.arc` format instead of adding a new file for this. before we engage in syntax debates we should document the particular use cases for configuration, carefully identify WHAT we're doing before enaging too much more on how they'll behave.

use cases being considered:

- environment variables that are safe to check into source control / 'default' env vars for the app
- opt into auto running architect/create at sandbox startup
- file paths for the sandbox init scripts
- file paths to watch for changes to reload the sandbox
- file paths to script to execute when the file paths to watch are changed

is this list complete / do we agree these are the goals  ?

**Comment by exalted** [comment]
Meta question perhaps, but… Do you really want _this_ level of configurability? I personally am okay with some hardcoded conventions as there benefits to have a natural (albeit "limited") structure to things…

For most of the points highlighted in the original discussion, I personally like to keep those concerns separate by adding external tools and scripts to make things work the way I like'em, rather than expect those features to be built-in.

* I think the possibility getting rid of the `.arc-env` file should be explored, and if it's required for sandbox only, I don't think it should be part of the app manifest. So, if really really really necessary, something like `.arc-sandbox` would be okay, which however at that point should include all other sandbox concerns as well, if any. (P.S.: I am not sure why `.arc-env` includes sections for staging and production environments, as that makes it impossible to include into git anyway.)
* Per function configuration files (i.e. `.arc-config`) IMO could be placed in the app manifest file instead.
* I like `arc sandbox` to generate new files for me when I change the app manifest file (not always, but most of the time), but if there will be a default to it and an option to toggle that default, I think I could be something like `arc sandbox --[no-]init` instead of a file property in the app manifest. (I am more than happy to include a CLI argument to my local development script, if that's all it takes.) :two-cents:
* 👎 for `arc sandbox` to watch for changes and/or reload itself (but I don't do HMR, so I am biased). I think this could potentially add more code to maintain in Architect [sandbox] and it's a concern that could be achieved (?) for local development with other tools such as https://github.com/Qard/onchange, https://github.com/watchexec/watchexec, etc.

**Comment by filmaj** [comment]
I like the idea of being able to define developer-experience options/customizations separately from app infrastructure/architecture. I see the purpose of the `.arc` file as formalizing the latter, and this proposal as an attempt at formalizing the former. With this kind of delineation in mind, it makes sense to me to keep these customizations stored in separate files.

Additionally, I think we should consider which of these various options/customizations apply globally to an arc developer's projects whenever using arc vs. ones that apply to a specific arc project. Things like sandbox autoinit I could reasonably see being a global option, but things like filesystem watcher scripts probably apply to specific projects. We could possibly lean on other software projects' local vs. global conventions for figuring out how to manage these (e.g. a project-specific .eslintrc file vs. a global one that sits in a user's home directory, and specificity of which options apply where depend on directory hierarchy).

We should also consider how these files would work with revision control. An arc project manifest must be checked into revision control as it defines an application to a massive degree, and must be shared amongst a team of devs, though the option to autoinit with sandbox probably should not be revisioned/shared to the same degree.

**Comment by ryanblock** [comment]
Finally landed this in Inventory today, say hello to `preferences.arc` (which will also soon be taking over for `.arc-config`): https://github.com/architect/inventory/pull/6/commits/36c29ef1d7866f74a5d376b00f31d5dddc4e7d41

I still need to go about implementing into individual libraries (starting with Sandbox), but aiming to ship an initial version in 8.2 (https://github.com/architect/architect/milestone/4) soon!

**Comment by ryanblock** [comment]
Shipping in 8.3.0 this week!
