### ISSUE TITLE
RFC: smarter code file paths 

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#806]
WIP! Rough Draft! Will be editing more later…today/tomorrow. 

Currently in Architect we favor convention over configuration. If you define `get /` we generate `src/http/get-index`. The `.arc`, `arc.json`, `arc.yaml`,  `arc.yml` or `arc.toml` file is the source of the truth and generates both infrastructure (s3, lambda, apigateway in this example) as well as initial source code. 

**This is nice.** Any developer knowledgeable about this behavior of Architect is immediately productive in any other Architect codebase. No debates about what to name things, no arguments about where to put files. Conventions free teams from [Parkinson's law of triviality](https://en.wikipedia.org/wiki/Law_of_triviality). 

But before we pat ourselves on the back too much we have to face that this is very Opinionated™ which is unnecessary polarizing. The problem is sometimes _our_ directory structure is not what people are expecting. Worse, they can't create these directories themselves; they need to run `arc init` to get them. We've built the code generation into the other commands (`sandbox`, `hydrate` and `deploy`) but this leads to unexpected directories sometimes being created also frustrating users.

## Proposal

First of all: we are not breaking anything. The original file structure and conventions are very good and scale to many hundreds of Lambda functions and are now in use by many thousands of apps. We are not breaking any of that.

## New capabilities 

- All core Architect primitives can take an optional path parameter to the source code as the last argument to a function definition (see below for an example)
- All core command line utilities will defer to the path in `.arc`, `app.arc`, `arc.json`, `arc.yaml`, `arc.yml` or `arc.toml` before falling back to the implicit behavior we've had since 1.x (sandbox, logs, ?)
- All core command line utilities (sandbox, hydrate and deploy, etc) no longer run `arc init` by default but can opt in by adding the flag `--init` (eg. `arc sandbox --init`)

## Example

In this example we'll specify the function code paths explicitly in `./functions/*`:

```
@app
myapp

@hydrate
views frontend # configure custom src/views path
shared functions/util # configure custom src/shared path

@static
folder dist # configure custom folder to sync with the s3 static bucket

@http 
get / functions/index
get /api/cats functions/api/cats
post /api/cats functions/api/cats
delete /api/cats functions/api/cats

@ws 
default functions/websockets/default
connect functions/websockets/connect
disconnect functions/websockets/disconnect
join functions/websockets/join

@scheduled
mantra rate(1 day) functions/mantra

@events 
ping functions/pingpong

@queues 
pong functions/pingpong

@tables
hits
  hitID *String
  stream functions/counter
```

**Comment by ryanblock** [comment]
> this is very Opinionated™
→ this is **apparently** very Opinionated™

To your point, thousands of projects are working fine with the current structure; Architect continues to grow week over week.

That said, let's talk about the idea. Here's a bunch of random thoughts.

---

**Readability**

As additional params, I think it's very hard to read and very verbose. Maybe folks want that, idk – perhaps to them the utility is far greater than all the noise it adds. Not me, but I'll curb that personal bias for the sake of conversation.

I think in order to properly evaluate this, we need to also show the json + yaml + toml implementations, too. What do those look like?

---

**Intentions of the Architect format**

A thing about the Architect format, whatever one's feelings about its benefits and faults, is that it was authored first to define app primitives in a simple, human-readable. It was not designed to be a format for building deep, heavy config – with intent, because Architect favors convention over configuration. (Example: many conversations about nesting below the second level.)

This feels like stretching the format pretty far, and it kind of shows. Now, perhaps I'm getting caught up in the presentation above, and we can mitigate that by something more like this:

```
@http 
get /
  functions/index
get /api/cats
  functions/api/cats
post /api/cats
  functions/api/cats
delete /api/cats
  functions/api/cats
```

I don't know, but I feel my above points still apply to that example. It feels pretty gnarly, like swimming upstream. Maybe other folks disagree though, and that's cool! Perhaps the utility outweighs the readability / maintainability concerns.

---

**Want vs. need**

Perhaps this is a thing a lot of people say they want, but then won't actually use. Hard to know – are we willing to take on whatever it takes to make the change just to find out that 

(See impacts of change below.)

---

**Impacts of change**

I think the degree of configurability here is immense, which means enormous bug vectors for us to take on.

Also means that when customers report bugs, we have a whole new layer of stuff to debug and diagnose – it's already difficult enough to get people to provide basic repro steps + arc file, now we're adding an entire filesystem dimension to that. Idk, maybe it'll be fine though.

**Customer impact**
Ideally little to none; nothing changes for current projects; everyone gets more (theoretical) configurability.

**Code impact**
About as big of an impact as any project we could realistically take on. In fact, I'm not sure I can think of a project with more scope.

We have to map everything in `inventory` to new individual dirs, and then ensure those mappings flow back into CloudFormation.

It will touch big, meaty chunks of critical path logic throughout `utils`, `package`, `parser`, `sandbox`, `hydrate`, `create` (aka `init`), `deploy`, and possibly smaller bits in `logs`, and other packages I'm not remembering.

I'll be honest, this scares me. Doesn't mean we shouldn't do it, but it does freak me out a bit.

**Docs impact**
Largely additive, but could make explaining things significantly more difficult.

**Comment by ljharb** [comment]
Solely as a “customer impact” data point: what i like about this (if I’m reading it right) is that i‘D be able to alter my routes without having to very carefully time renaming my route folder and running my next arc command - iow, the arbitrary names i choose for parameters needn’t be reflected directly in the filesystem - yet the source of truth will remain in the arc config. If this was available, I’d immediately refactor to use it.

**Comment by ryanblock** [comment]
@ljharb yeah that’s about right! A question:

What do you mean by `very carefully time renaming my route folder and running my next arc command`?

Right now the process is: change the arc route, change the folder; it’s deterministic and deploys fail loudly when expected folders aren’t present, so I’m wondering what seems brittle?

**Comment by ljharb** [comment]
When I'm developing locally, I have a tab running with `npm start` at all times, and this seems to at times create the folders matching the new spelling before I've remembered to rename the folders from the old one.

In particular, I constantly forget I *need* to rename the folders, since it's very atypical for renaming a route to necessitate any changes anywhere else besides in the code for the route, so this might be my main problem :-)

**Comment by brianleroux** [comment]
quick update to address/discuss some of the comments.

## readability 
per ryan's comments how does this look in other dialects?

first of all a complete example using `app.arc` or `.arc` native synax. things to notice: 
- all lambda definitions are still on one line
- you can format the indentation to improve scanning
- hydrate gets a special pragma for views/shared
- this is backwards and forwards compatible without bumping MAJOR (additive non breaking)

```
@app
myapp

@hydrate
views frontend # configure custom src/views path
shared functions/util # configure custom src/shared path

@static
folder dist # configure custom folder to sync with the s3 static bucket

@http 
     get /               functions/index 
     get /api/cats  functions/api/cats
   post /api/cats  functions/api/cats
delete /api/cats  functions/api/cats

@ws 
       default functions/websockets/default
     connect functions/websockets/connect
disconnect functions/websockets/disconnect
            join functions/websockets/join

@scheduled
mantra rate(1 day) functions/mantra

@events 
ping functions/pingpong

@queues 
pong functions/pingpong

@tables
hits
  hitID *String
  stream functions/counter
```

The 'default' JSON version would initially be just using default architect/parser json ouput (and not make any changes/additions to the cardinality or introduce new syntax keywords so as to not introduce any breakage or additional work initially…this doesn't opt us out of doing those changes in the future such as adding a keyword 'code' or 'folder' to http functions, for example):

```json
{ 
  "app": "myapp",
  "http": [
    ["get", "/", "functions/index"],
  ],
  "ws": [
     ["default", "functions/websockets/default"],
     ["connect", "functions/websockets/connect"],
     ["disconnect", "functions/websockets/disconnect"]
  ],
  "scheduled": [
     ["mantra", "rate(1 day)", "functions/mantra"]
  ],
  "events": [
    ["ping", "functions/pingpong"]
  ]
}
```

(TOML and YAML would be essentially the same.)

## Impact of change

if we follow the idea that this is an additive change to the format by always using the 'last param' in lambda one liner config then we can slowly opt downstream modules in. here's an ordered list of what happens:

- `architect/parser` - need to update `schema.json`
- `architect/package` - already prototyped in a macro and branch; changes in 11 files to lookup CodeUri
- `architect/functions` - no changes
- `architect/sandbox` - need to change all lookup logic
- `architect/utils` - ideally we're removing this repo by re-consolidation not adding to it or changing it; many/most helpers in here are only use by one module but all modules share this larger dep. if there is a helper in use by many modules we should make itself a dedicated module rather than a junk drawer. (eg. architect/inventory) and otherwise would like to move things back to where they are used. should open a fresh issue for this refactoring.
- `architect/deploy` def needs to change its lookup logic for dirty deploys; sam deploy uses `architect/package`
- `architect/env` needs to know how reverse lookup function logs from local path
- `architect/hydrate` needs to know how to find function paths
- `architect/create` needs to know how to find function paths
-  `architect/repl` no change
-  `architect/destroy` no change

### future
- Add syntax to JSON/YAML/TOML for more explicit defns (eg. `{get: '/', code: '/functions/foo'}`)

**Comment by filmaj** [comment]
I like it as an option and particularly as @ryanblock pointed out as a way of creating templates for migrating over from other frameworks.

I don't think I'd use it myself, though, I'm happy with the defaults.

**Comment by andybee** [comment]
I can see the pros and cons of this proposal,  but I am quite excited by the flexibility it offers with matching routes to functions if (and only if) you want to get that deep in to configuration.

**Comment by ryanblock** [comment]
Related to shoring up some logic for function config I've been looking at this again; @brianleroux and I worked through another (additive) approach to function configurability, which is to make each function an Arc object, and possibly add some optional higher-level shared root dir for code (equivalent to `src` today):

```
@config
rootdir functions

@http 
/
  method get
  srcdir web/index
/foo
  method get
  srcdir web/index # Shares all code with get /
/bar
  method get
  srcdir web/bar
/baz
  method get
  srcdir web/baz
/buz
  method get
  srcdir web/buz

@ws 
default
  srcdir websockets/default
connect
  srcdir websockets/connect
disconnect
  srcdir websockets/disconnect
join
  srcdir websockets/join

@scheduled
mantra
  rate 1 day
  srcdir scheduled/scheduled

@events 
ping 
  srcdir pingpong

@queues 
pong 
  srcdir pingpong
```

Any thoughts on that vs a 3rd (or 4th) parameter on existing functions?

**Comment by andybee** [comment]
This would be a good solution to what I wrote in #826 where I'd like to write a shared codebase for PUT, DELETE and POST so I can write methods for PUT and DELETE directly, then wrap them up with fallback POST support.

**Comment by ryanblock** [comment]
Finally shipping in 8.3! Also @andybee: what you requested totally works!
