### ISSUE TITLE
RFC: @architect/utils unbundling

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#836]
In https://github.com/architect/architect/issues/806 a sidebar came up about unbundling `@architect/utils` into individual modules: 

From @brianleroux:
> `architect/utils` - ideally we're removing this repo by re-consolidation not adding to it or changing it; many/most helpers in here are only use by one module but all modules share this larger dep. if there is a helper in use by many modules we should make itself a dedicated module rather than a junk drawer. (eg. architect/inventory) and otherwise would like to move things back to where they are used. should open a fresh issue for this refactoring.

Disagree `@architect/utils` is a junk drawer, and personally I think it's nice not to have to maintain and have the noise of 5-7 additional tiny modules in support of our core dependencies, but I do appreciate the point about keeping things single responsibility.

In any event, a quick rundown:

`banner` used by:
- All commands via `@architect/architect`
- Any commands that can run independently of `@architect/architect`:
  - `@architect/create`
  - `@architect/deploy`
  - `@architect/sandbox`

`chars` used by:
- `utils/banner`
- `utils/updater`

`fingerprint` used by:
- `@architect/deploy`
- `@architect/package`
- `@architect/sandbox`

`get-lambda-name` used by:
- `@architect/package`

`get-layers` used by:
- none (I think)

`init-env` used by:
- @architect/sandbox`

`inventory` used by:
- `@architect/deploy`
- `@architect/hydrate`
- `@architect/macro-node-prune`
- `@architect/sandbox`

`path-to-unix` used by:
- `@architect/deploy`
- `@architect/sandbox`

`port-in-use` used by:
- `@architect/sandbox` (should probably be moved just into sandbox)

`to-logical-id` used by:
- `@architect/deploy`
- `@architect/macro-storage-public`
- `@architect/macro-storage-private`
- `@architect/package`

`updater` used by:
- `@architect/architect`
- `@architect/create`
- `@architect/deploy`
- `@architect/env`
- `@architect/hydrate`
- `@architect/logs`
- `@architect/macro-node-prune`
- `@architect/repl`
- `@architect/sandbox`

`validate` used by:
- none (I think)

**Comment by filmaj** [comment]
I'm ambivalent on this. Factoring out the methods into individual modules feels like make-work, but if someone where to do it, I wouldn't stand in their way.

Everyone has a junk drawer at home, right? It _does_ serve a purpose.

**Comment by ryanblock** [comment]
I was recently poking through utils on the lookout for stuff to retire now that Architect has settled down post 6 rewrite last year – it definitely does make sense to me to clean up some of the junk that's in utils, and I've been plucking things off one by one in anticipation of getting lots of clearance so we can clean out the actual junk from the drawer.

Re breaking things out, I think all things being equal, I'm biased towards single utils repo == fewer deps to manage && fewer things to update (CoC, readmes, etc) && fewer things to deploy / publish, etc.

**Comment by brianleroux** [comment]
Going to ignore analogies that fall apart (like junk drawers) because they're supposed to communicate an idea and are easily defeated as an argument with literal interpretation. ;) I also ack this isn't how things are right now so I want to try to convey a goal state. Its ok we have utils. Its probably going to be around a while! It would be ideal (for me) if we worked towards not having it however. 

The core trade off of a utils or helpers or whatever grab-bag is the same problem as a monorepo. It trades off composition for the appearance of ease of reuse. It costs us in having a hard to decipher dep tree and tightly couples otherwise separated concerns making it harder to release/reason about the larger system. All of these deps could be either single responsibility OR moved into the functional sphere of responsibility they belong to (even by copy/paste in some cases…this is ok!). This is normal and natural evolution from monorepo to single responsibility and very often finding balance feels like being on a pendulum of tradeoffs.  

Rather than continuing to restate this in different ways I'll take a stab at demonstrating what I mean by going through each dep below. But before I do want to communicate a few goals:

- Ideally the main repo is the main CLI and should be the only thing that logs to stdout or has any other side effects
- All the other repos should be modules only that accept args and return values only 
- Modules should only have have one entry
- Modules that can be platform agnostic (pure JS) should be (esp important for modules that have no hard requirement for disk or network)

Again I realize we're not there today. Just identifying good ways to move forward. Here's my ideas (not mandates) for discussion:

- `banner` belongs to the main cli/repo and really shouldn't be required elsewhere
- `chars` belongs to updater (which I think should maybe be its own repo)
- `fingerprint` belongs to `@architect/deploy` and should only be required in there
- `initEnv` only used by sandbox so it should only be in sandbox…but moreso I don't think we should auto create deps anymore; ideally we give clear errors when things are missing
- `portInUse` move back into `@architect/sandbox` since its the only place using it
- `getLayers` should be copied into the places using it (too small to warrant reuse like this)
- `getRuntime` likewise
- `pathToUnix` (think this is only a deploy concern but maybe also sandbox?)
- `readArc` (already moved back into `@architect/parser` … all deps should use that version)
- `getLambdaName` belongs to `@architect/package` and should be moved into there
- `toLogicalID` belongs to `@architect/package`

Things that have broad use that should have their own repo:

- `inventory`
- `validate` 

Things I'm not sure about:

- updater could be its own repo but could also be considered the bulk of the logic the main cli/app entry `@architect/architect` and passed into sub deps for event emitter style logging (removing stdout calls from sub repos and lifting them up to the one place that needs to do that) this is such an important module now that it basically is the user experience for the CLI.

**Comment by ryanblock** [comment]
Quick update: we now have two things in Package that need to be broken out for reuse (which is how this issue came back up again over this weekend):
- Function config rewrite I did last week (https://github.com/architect/package/blob/master/src/visitors/get-lambda-config.js) needed in both Deploy (to fix https://github.com/architect/architect/issues/866) and Sandbox (which has out of date / inconsistent config logic)
- `@tables` parameter cleaner (https://github.com/architect/package/blob/master/src/visitors/tables/clean.js) as a better fix for https://github.com/architect/architect/issues/785 and other related table param issues; to be reused in Sandbox (see https://github.com/architect/sandbox/pull/340#issue-412401993 via @filmaj)

**Comment by filmaj** [comment]
I appreciate the modularity, adherence to functional program purity and reduction of coupling that you describe @brianleroux. I support all of those characteristics of the ideal end-state!

I can get behind unbundling utils, I'm just lazy and not looking forward to doing that work 🥴

**Comment by ryanblock** [comment]
An update: this may be a thing we'll want to do later, but Inventory-aware Utils 2.0 is now _seriously_ pared down:
- Removed methods that are now the responsibility of Inventory:
  - `fingerprint.config`
  - `getLayers`
  - `getRuntime`
  - `inventory`
  - `read`
  - `readArc`
  - `validate`
- Removed methods no longer in active use by any Architect projects:
  - `initEnv`
  - `portInUse`

Closing for now!
